---
# tasks file for collectd-role

- name: All | Check variables status
  include_tasks: check.yml
  
- name: ReHat | Include install tasks
  include_tasks: install-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: RedHat | Include customize tasks
  include_tasks: customize-RedHat.yml
  when: ansible_os_family == "RedHat"