---
# tasks file for collectd-role

- name: Install EPEL Release
  yum:
    name: epel-release
    state: installed
  become: true

- name: Install Python-PIP and Setuptools
  yum:
    name: python-setuptools, python-pip
    state: installed
  become: true
  
- name: Install collectd packages
  yum:
    name: collectd, collectd-apache, collectd-smart
    state: installed
  become: true

- name: Genereate collectd config file
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
  become: true

- name: Create plugins folder
  file:
    path: /opt/collectd-plugins
    state: directory
  become: true

- name: Upload custom python plugins
  copy:
    src: plugins/
    dest: /opt/collectd-plugins
  become: true

- name: Ensure setuptools is installed
  pip:
    name: setuptools
  become: true

- name: Install collectd python package
  pip:
    name: collectd
  become: true

- name: Enable and start collectd service
  service:
    name: collectd
    state: restarted
    enabled: yes
  become: true